all:
	cc -Wall -Werror -Werror -g my_ascii_to_int_ptr.c ft_isdigit.c ft_lstadd_front.c ft_lstdelone.c \
	ft_lstnew.c ft_strdup.c push_swap.h ft_lstadd_back.c \
	ft_lstclear.c  ft_lstlast.c ft_lstsize.c push_swap.c \
	my_has_dup.c ft_lstmap.c my_put_err.c operations.c 
