all:
	cc -Wall -Werror -Werror -g ft_atoi.c ft_isdigit.c ft_lstadd_front.c ft_lstdelone.c \
	ft_lstnew.c ft_strdup.c push_swap.h ft_atoi_s.c ft_lstadd_back.c \
	ft_lstclear.c  ft_lstlast.c ft_lstsize.c push_swap.c ft_itop.c \
	ft_hasdup.c
